font:
  # The normal (roman) font face to use.
  normal:
    family: "Fira Code"
    #family: "Hack Nerd Font"
    # Style can be specified to pick a specific face.
    style: Bold
window:
  decorations: buttonless
  opacity: 0.75
