add_newline = false

format = """
$custom\
$all\
$kubernetes\
$fill \
$time\
$line_break\
$character
"""

[fill]
symbol = " "

[username]
style_user = "213 bold"
style_root = "bright-red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[line_break]
disabled = false

[character]
success_symbol = "[I](bold 46)"
error_symbol = "[✗](bold 196)"
vicmd_symbol = "[N](bold 46)"
format = "$symbol [❯](bold 39)  "

[directory]
read_only = " "
truncation_length = 8
truncate_to_repo = false
truncation_symbol = "…/"
style = "99 bold"

[kubernetes]
disabled = false
style = "213 bold"
format = 'on [⛵ $context( \($namespace\))]($style) '

[kubernetes.context_aliases]
"arn:aws:eks:eu-central-1:.*:cluster/staging" = "staging"
"arn:aws:eks:eu-central-1:.*:cluster/tatooine" = "tatooine"
"arn:aws:eks:eu-central-1:.*:cluster/production" = "production"
"arn:aws:eks:eu-central-1:.*:cluster/bonfire" = "home-k8s"
"arn:aws:eks:eu-central-1:.*:cluster/mug" = "mug"


[time]
disabled = false
use_12hr = false
format = '[ $time ]($style) '
time_format = "%T"
utc_time_offset = "local"

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
# symbol = "☁️ "
symbol = "🌨️  "

[git_status]
conflicted = "🏳"
ahead = "🚀"
behind = "😰"
diverged = "😵"
untracked = "🤷"
stashed = "📦"
modified = " 🦄 "
staged = '[++\($count\)](green)'
renamed = "🚶"
deleted = "🗑 "

